#!/bin/bash

echo "Adding the updated files..."
GitAdd=$(git add .)
echo "Process completed adding the file"

read -p "Please mention the commit title : " commit_message

echo "Thank you"
echo "Commiting now"
echo "Processing now ........"

CommitOutput=$(git commit -m "$commit_message" | tail -n 1)

echo " Process completed"
echo " Now pushing the completed the file"

FilePush=$(git push | grep -E "completed with)
